name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # تغيير لـ master إذا كنت تستخدمه

permissions:
  contents: write  # ضروري للكتابة على فرع gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # استخدام الإصدار الأحدث
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20  # استخدام إصدار أحدث من Node
        
    # تخطي هذه الخطوة إذا لم يكن لديك package.json
    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci  # أسرع من npm install
        fi
        
    # تخطي إذا لم يكن لديك أمر بناء
    - name: Build project
      run: |
        if [ -f "package.json" ]; then
          npm run build --if-present
        else
          echo "No build step required"
        fi
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4  # الإصدار الأحدث
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: false  # لضمان نظافة الفرع
        force_orphan: true  # إنشاء فرع جديد نظيف كل مرة
