name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # يتم التشغيل فقط عند الدفع إلى الفرع الرئيسي

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js (required by some actions)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Copy public folder to root
        run: |
          mkdir temp-deploy
          cp -r public/* temp-deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp-deploy
          publish_branch: gh-pages
          force_orphan: true
